### PR TITLE
Baby's First Drivetrain + Readme and Contributers

### PR DESCRIPTION
**Pull request by Liam-Wirth**
I wrote the Base drive train with tank drive, I followed the guide and had to fix some outdated info left in the guide, all the code is documented. 
I'll probably write swerve drive later this week

### CODE REVIEW

**Review by ksthakkar — COMMENTED** [review]
Create differential drive object outside of the run method, as that will be called periodically (in Ms) during the match. Recommended to do it during first initialization along with the motors

**Comment by ryanchaiyakul** [comment]
Also, fix your indentation and spacing within the DriveTrain.java file.

**Comment by Liam-Wirth** [comment]
that should be everything fixed, I created a constants class, and also moved stuff into the teleopinit method

**Review by ksthakkar — APPROVED** [review]
Looks good 👍

**Pull request merged**
